// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqnxbckdxvfkjyhrfthp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxbnhiY2tkeHZma2p5aHJmdGhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwMTAxMDYsImV4cCI6MjA4NTU4NjEwNn0.mx31hTck8KNcUVQFS2pO1ZDb7BJfge40Nlc4_-G0hHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});